events {
    worker_connections 1024; # default max number of simultaneous connections per nginx process 
}

http {
    # MIME TYPES - this is needed for CSS/JS  content type so browsers can render them correctly
    include /etc/nginx/mime.types; # a file that maps file extensions to content types ,come with nginx
    default_type application/octet-stream; # default content type for unknown file types

    server {
        listen 80;

        # React frontend - serve static files
        location / { 
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Spring Boot API - proxy all /api/* requests to spring boot container  
        location /api/ {
            proxy_pass http://backend:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
