import react from '@vitejs/plugin-react';
import { fileURLToPath } from 'node:url';
import { defineConfig, loadEnv } from 'vite';

const srcPath = fileURLToPath(new URL('./src', import.meta.url));

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');
  const apiTarget = env.VITE_API_TARGET ?? 'http://localhost:8080';

  return {
    plugins: [react()],
    resolve: {
      alias: {
        '@': srcPath,
      },
    },
    // Use esbuild for CSS minification to avoid lightningcss warnings
    // with custom rules generated by PostCSS plugins.
    build: {
      cssMinify: 'esbuild',
    },
    server: {
      proxy: {
        // any request starting with /api will be forwarded to the Spring Boot backend 
        // adding logging to proxied requests for easier debugging

        '/api': {
          target: apiTarget,
          changeOrigin: true,
          secure: false,
          
          //log proxied requests and errors 
          /*
           configure: (proxy, options) => {
            proxy.on('proxyReq', (proxyReq, req, res) => {
              console.log(`[Proxy] ${req.method} ${req.url} -> ${apiTarget}${req.url}`);
            });
            proxy.on('error', (err, req, res) => {
              console.error(`[Proxy Error] ${req.method} ${req.url}:`, err);
            });
          }, */
        },
      },
    },
  };
});